"""
Module II & III: Simulation Engine
Generates the LAMMPS input script and executes the simulation.
"""

import subprocess
import sys
from pathlib import Path

def generate_input_file(
    data_file: Path,
    input_file: Path,
    output_dump: Path,
    steps: int = 10000,
    temp: float = 300.0,
    damp: float = 20.0,
    epsilon: float = 0.105, # Global scale if needed, but we'll use specific ones
    sigma: float = 2.5,
    timestep: float = 1.0
):
    """
    Writes the simulation.in file for LAMMPS with CHONS support.
    """
    
    # OPLS-AA inspired Non-bonded parameters
    # Type mapping: 1=C, 2=H, 3=O, 4=N, 5=S
    pair_params = {
        1: (0.066, 3.50),  # C
        2: (0.030, 2.50),  # H
        3: (0.170, 3.12),  # O
        4: (0.170, 3.25),  # N
        5: (0.250, 3.55)   # S
    }

    content = f"""# LAMMPS Input file generated by Proteus (CHONS Forcefield)

units real
atom_style full
boundary p p p

read_data {data_file.absolute()}

# Force Field
pair_style lj/cut 10.0
pair_modify mix arithmetic
"""
    # Write pair coefficients
    for t, (eps, sig) in pair_params.items():
        content += f"pair_coeff {t} {t} {eps} {sig}\n"

    content += f"""
bond_style harmonic
# 1: Single, 2: Double, 3: Triple, 4: Other
bond_coeff 1 300.0 1.54
bond_coeff 2 500.0 1.34
bond_coeff 3 700.0 1.20
bond_coeff 4 400.0 1.40

angle_style harmonic
angle_coeff 1 60.0 109.5

neighbor 2.0 bin
neigh_modify delay 0 every 1 check yes

# Group definitions
group all_atoms type 1 2 3 4 5

# Simulation Protocol
minimize 1.0e-4 1.0e-6 100 1000
reset_timestep 0

timestep {timestep}

# 2. Equilibration / Dynamics
fix 1 all langevin {temp} {temp} {damp} 48279
fix 2 all nve

# Output
dump 1 all custom 50 {output_dump.absolute()} id mol type x y z
compute rg all gyration
thermo_style custom step c_rg temp epair
thermo 100

# Run
run {steps}
"""
    with open(input_file, 'w') as f:
        f.write(content)
    
    print(f"[*] Input file written to {input_file}")

def run_simulation(input_file: Path, log_file: Path):
    """
    Executes LAMMPS simulation.
    """
    print(f"[*] Starting LAMMPS simulation: {input_file.name}")
    
    cmd = ["lmp", "-in", str(input_file), "-log", str(log_file)]
    
    try:
        # Capture output to suppress huge logs but show errors
        result = subprocess.run(
            cmd, 
            stdout=subprocess.PIPE, 
            stderr=subprocess.PIPE, 
            text=True, 
            check=True
        )
        print("[*] Simulation completed successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error: LAMMPS failed with exit code {e.returncode}")
        print(e.stderr)
        sys.exit(1)
    except FileNotFoundError:
        print("Error: 'lmp' executable not found. Ensure LAMMPS is installed and in PATH.")
        sys.exit(1)

if __name__ == "__main__":
    pass
